name: cyber_sec
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  crypto: ^3.0.6
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/google_fonts/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/cyberSec.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/cyberSec.png"
  windows:
    generate: true
    image_path: "assets/cyberSec.png"
    icon_size: 256 # min:48, max:256, default: 48

